[project]
name = "pyqt6-starter"
version = "0.1.0"
description = "Starter template for a PyQt6 desktop app"
requires-python = ">=3.10"
dependencies = [
	"PyQt6==6.9.1",
]

[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
select = ["E", "F", "I"]
fix = true

[tool.ruff.lint.isort]
known-first-party = ["app"]

